name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Stockholm
          repositories_forks: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 1079901
          plugin_stackoverflow_sections: ''
          plugin_stackoverflow_lines: 0
          plugin_projects: yes
          plugin_isocalendar: yes
